### ISSUE TITLE
Error when running CMake

### ISSUE THREAD

**Issue by gloa7** [ike3/mangosbot#102]
Attempting to install mangosbot using the instructions on the trinitycore installation guide I receive the following error:
```
CMake Error at src/modules/CMakeLists.txt:23 (add_subdirectory):
  The source directory

    /home/wow-server/mangosbot/src/modules/Bots

  does not contain a CMakeLists.txt file.


CMake Error at src/modules/CMakeLists.txt:28 (add_subdirectory):
  The source directory

    /home/wow-server/mangosbot/src/modules/Immersive

  does not contain a CMakeLists.txt file.


CMake Error at src/CMakeLists.txt:35 (add_subdirectory):
  The source directory

    /home/wow-server/mangosbot/src/test

  does not contain a CMakeLists.txt file.


-- Configuring incomplete, errors occurred!

```

Is there any reason why this might be? In both modules/Bots & modules/Immersive there are no files by default.

**Comment by gloa7** [comment]
It seems I've alleviated this by cloning the different repos that are the src/test, src/modules/Bots, and src/modules/Immersive
Am I missing a step in all this? I cloned the base repo than began trinitycore installation steps, this is on debian11 with all requirements installed.

**Comment by Dids** [comment]
@gloatoriginal Did you actually solve this? I can't seem to find any definitive information on whether or not any of this should still work with TrinityCore directly.

**Comment by gloa7** [comment]
@Dids If I did come up with an actual solution I'm unsure what it is now, as I haven't tinkered with this in a bit, I do recall having bots in the end, but not sure steps taken fully.
