### ISSUE TITLE
Wndows 8.1 shits again

### ISSUE THREAD

**Issue by conan513** [ike3/mangosbot#13]
Some settings doesn't have effect when I change it on Windows 8.1.

Example:
randomBotLoginAtStartup = config.GetBoolDefault("AiPlayerbot.RandomBotLoginAtStartup", true);

AiPlayerbot.RandomBotLoginAtStartup = 1

default all bots login on server start but this do heavy lag and I wanna disable this so I change in the config file first but no effect, then I changed in the code to false but nothing and all bots login on start

**Comment by Kittnz** [comment]
It works for me, it only takes a few minutes so everything gets loaded. Tons of sql errors tho but i fixed those. I still have to redo the PR.

**Comment by ike3** [comment]
Actually I experience better performance on TC comparing to R2. The lag exists but no longer than 10-20 secs just after server start until all bots logged in.

**Comment by conan513** [comment]
I forget to say I have lag only when I start the server first time and it's start to generate bots

**Comment by ike3** [comment]
I see. This is due to randomization process. It is recommended to give console command

```
rndbot init
```

after the database installation so all bots will be randomized at once. All futher randomizations are incremental and won't  cause lag anymore.
