### ISSUE TITLE
AH Bot Trinity Core Default

### ISSUE THREAD

**Issue by dmanbob** [ike3/mangosbot#16]
ike3 is there anyway to mod so you can use the Trinity Core AH Bot by default and exclude bots from buying or selling? I think this might improve performance and lag. Since this is a single player experience I don't care who post auctions as long as I can sell and buy items in the AH.

**Comment by ike3** [comment]
This is possible but I don't think AhBot causes any lag. It works in separate thread so server processing continues during check cycles. You can give 'ahbot update' console command and see other commands are prosessed even the update is not finished yet.

**Comment by dmanbob** [comment]
OK thanks I will check but I do seem to get way more lag with the AH enabled. Also doesn't seem to fill the Auction house with the number of items I enter in the configs but that could be my part on learning all the tweaks of the new AH bot config, I'm used to the old Trinity AH bot setup.

**Comment by dmanbob** [comment]
With new version today lag seems gone now. One thing I noticed though is AH does not seem to fill to anywhere max items I suggest in the config. Is this because I only have 125 bots and they are only going to post one or two items each? At least with the Trinity AHbot it posted the max items in the config :)  On the flip side it's cool to see different names in the AH rather than just AHbot :) You can close the thread after you respond thanks.

**Comment by ike3** [comment]
AH will not always be filled. If an item is posted it won't be post again until some time is passed. This interval depends on item's rarity so blue and epics are rare to see in the AH.
If player missed an opportunity to buy the item He forced to wait for a while. Imagine that another player just bought the item and there is nothing more to offer at the moment.
The actual algorithm is a bit more complex involving splitting items into categories, price fluctuaions, market price calculation etc. E.g., if an item is in demand, the price will rise. Sometimes some bot could offer much lower price for random item so if somebody is lucky he can re-sell it and make profit.

**Comment by dmanbob** [comment]
OK thanks for the input to my questions much appreciated. Perhaps as a wish list giving the option to use regular Trinity AHbot or yours would be cool
