### ISSUE TITLE
Random Bots unused Talent points

### ISSUE THREAD

**Issue by cacodaemonic** [ike3/mangosbot#18]
I have been running around with the same group of random bots from level 10 to level 15ish.  I have been taking them to the trainers at level ups.  They have been learning spells but they are not allocating talent points. This is seen when I inspect them.  I was looking through the commands and didn't see a way to select their talent points.  Is this normal, that talent points on the random bots have no easy way to allocate?

**Comment by ike3** [comment]
They should be allocated randomly at levelups. Just disband your group and after some times they should be set.

   rndbot refresh <bot_name>

can be used to force refresh without waiting

**Comment by cacodaemonic** [comment]
Thx.  A refresh fixed that.
