### ISSUE TITLE
Can't seem to get players from guild or account to join as bots

### ISSUE THREAD

**Issue by dmanbob** [ike3/mangosbot#20]
In latest version can not seem to add playerbots using .bot add command
Tried all config settings, this worked in previous versions could at least get guild members to join, but nothing works now.
.bot add xxx
error
add: xxx not allowed

**Comment by ike3** [comment]
It works for me (at least for account). But I noticed that player names are case-sensetive in TC. So

```
.bot add xxx
```

won't work but 

```
bot add Xxx
```

will do

**Comment by dmanbob** [comment]
OK tried it case works for Guild members only can't get non guild members to join are your account players in your guild too?

**Comment by ike3** [comment]
Added some friendly error messages in [ai-0.36-69]

**Comment by dmanbob** [comment]
OK great yeah it seems only guild member I can add in whether they are in my account or other accounts :)

**Comment by dmanbob** [comment]
Another note if someone changes the config to AiPlayerbot.AllowGuildBots = 0 and they try and add a bot from the guild the server crashes immediately

**Comment by ike3** [comment]
Can you post the crash dump?

**Comment by dmanbob** [comment]
I shut down for the night but I will tomorrow

**Comment by dmanbob** [comment]
cannot replicate issue perhaps it was just after I restarted server. Now it seems fine it just won't let you invite them if you set  AiPlayerbot.AllowGuildBots = 0

**Comment by dmanbob** [comment]
did it on latest build with flag on this time AiPlayerbot.AllowGuildBots = 1 when I tried to invite non guild bot, I'm just checking dmp now could be an issue with my PC.

**Comment by ike3** [comment]
Tested it on the latest build:

Thunter and Trogue - two chars from different accounts.

```
.guild create "Test guild" Thunter
.guild invite Trogue "Test guild" 
```

From Thunter

```
.bot add Trogue
```

ok

Changed AiPlayerbot.AllowGuildBots = 0 (which is not default)

From Thunter

```
.bot add Trogue
```

You are not allowed to control bot Trogue
