### ISSUE TITLE
Errors: error creating guild task

### ISSUE THREAD

**Issue by Kittnz** [ike3/mangosbot#26]
Bug:
The Blade / Subfusion: error creating guild task
The Gnomes Lordaero / Subfusion: no items avaible for item task
The Gnomes Lordaero / Subfusion: error creating guild task
Raven Clan / Subfusion: no items avaible for item task
Raven Clan / Subfusion: error creating guild task
Raiders of the Sil / Subfusion: no items avaible for item task
Raiders of the Sil / Subfusion: error creating guild task
The Blues Azeroth / Subfusion: no items avaible for item task
The Blues Azeroth / Subfusion: error creating guild task
The Red Hood Thunder / Subfusion: no items avaible for item task
The Red Hood Thunder / Subfusion: error creating guild task

I'm getting these errors all the time. Subfusion is my gm character and the only normal client that is connected to the server. It keeps spamming this all the time. I do have a guild on that char but not these bot clans.

Any ideas?

Core: eb577316d1819539599815c495b9129660f9f988

**Comment by ike3** [comment]
Seems the server cannot pick an item for a proper guild task. Do you have auction bot enabled? Guild Tasks is an experimental feature and relies on ahbot for item prices.

**Comment by Kittnz** [comment]
Yes i am using the auction bot. So i don't know whats wrong with that. Ill retest later just to be sure.

**Comment by Kittnz** [comment]
It's fine, no errors anymore.
