### ISSUE TITLE
Error Building ../Ahbot/AhBot.h

### ISSUE THREAD

**Issue by krlloyd** [ike3/mangosbot#27]
Having issue building complains that that it cannot find AhBot.h.

Builds on earlier commit.

**Comment by Kittnz** [comment]
There is no earlier commit... please give us details so we can help.
Update your core and make an issue ticket.

**Comment by krlloyd** [comment]
I checked out 5474ed1 and was able to build the project. I did this on a debian based server.I will see if i can reproduce this error on a windows box.

Someone else was also having this error: http://www.trinitycore.org/f/topic/10411-mangos-bot-former-playerbot-ai/page-2#entry69609

Thanks for your prompt response!

**Comment by krlloyd** [comment]
Placed pull request with fix.

**Comment by ike3** [comment]
Thanks!
