### ISSUE TITLE
On make install - bot configs are not created

### ISSUE THREAD

**Issue by krlloyd** [ike3/mangosbot#29]
aiplayerbot.conf.dist and ahbot.conf.dist not installed during the make install process. I verified that the issue exists in windows as well as linux. The aiplayerbot.conf.dist.in and the ahbot.conf.dist.in files are present in the repository.

**Comment by krlloyd** [comment]
Updating the plugins cmake file to install the missing config files.

**Comment by ike3** [comment]
Merged the PR
