### ISSUE TITLE
SmartScript Crash [Linux]

### ISSUE THREAD

**Issue by Talmeron** [ike3/mangosbot#31]
SmartScript: Action target Creature (GUID: 31877 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 31877 Entry: 5743) skipped to prevent crash.
SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.
SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.
SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.
SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.
SmartScript: Action target Creature (GUID: 45218 Entry: 5743) is not using SmartAI, action called by Creature (GUID: 45218 Entry: 5743) skipped to prevent crash.
Killed

**Comment by ike3** [comment]
I don't think this has anything common with bots. 

```
select * from tc_world.creature_template where entry = 5743;
```

It's a Caged Sheep: http://www.wowhead.com/npc=5743/caged-sheep. I'd suggest you post this issue to TC core itself.

**Comment by Talmeron** [comment]
Running a copy of vanilla TC 3.3.5 and not having any issues.
