### ISSUE TITLE
Core: Lagging

### ISSUE THREAD

**Issue by Kittnz** [ike3/mangosbot#33]
Bug: core is unstable and lags a lot. I had this since the beginning and at first i thought it was because the load of the random npc's that are spawning, but after leaving it up for an hour, not be able to login and if i am able to login the server just hangs. It seems it does do stuff but it lags tons and tons and it is not playable.

Normal trinitycore build works perfect with no lag issues.

Any idea's?

**Comment by TheJrod** [comment]
I had the same problem one day. I tried to turn off the Ahbot in the ahbot.conf

"Replace with the new AhBot
AhBot.Enabled = 0"

Then my lag stopped.

But afterwords i have had this enabled again, and the server only lags in the beginning, but about 10 - 15 minutes after its started, its working just fine.

**Comment by Kittnz** [comment]
I'll check, thanks!

**Comment by Kittnz** [comment]
That fixed it, thanks for the responds!
