### ISSUE TITLE
Ubuntu 14.04 compile error

### ISSUE THREAD

**Issue by momokli** [ike3/mangosbot#39]
When I try to compile on Ubuntu, the following error appears:

[  2%] Built target jemalloc
[  6%] Built target g3dlib
[  6%] Built target Detour
[  7%] Built target Recast
[  7%] Built target gsoap
[  8%] Built target mpq
[  8%] Built target revision.h
[ 10%] Built target shared
[ 10%] Building CXX object src/plugins/CMakeFiles/plugins.dir/playerbot/RandomPlayerbotFactory.cpp.o
In file included from /home/trinity/mangosbot/src/plugins/playerbot/RandomPlayerbotFactory.cpp:2:0:
/home/trinity/mangosbot/src/plugins/playerbot/playerbot.h:3:1: error: ‘vector’ in namespace ‘std’ does not name a type
 std::vectorstd::string split(const std::string &s, char delim);
 ^
compilation terminated due to -Wfatal-errors.
make[2]: **\* [src/plugins/CMakeFiles/plugins.dir/playerbot/RandomPlayerbotFactory.cpp.o] Error 1
make[1]: **\* [src/plugins/CMakeFiles/plugins.dir/all] Error 2
make: **\* [all] Error 2

make install obviously encounters a similar error:
[  2%] Built target jemalloc
[  6%] Built target g3dlib
[  6%] Built target Detour
[  7%] Built target Recast
[  7%] Built target gsoap
[  8%] Built target mpq
[  8%] Built target revision.h
[ 10%] Built target shared
[ 10%] Building CXX object src/plugins/CMakeFiles/plugins.dir/playerbot/RandomPlayerbotFactory.cpp.o
In file included from /home/trinity/mangosbot/src/plugins/playerbot/RandomPlayerbotFactory.cpp:2:0:
/home/trinity/mangosbot/src/plugins/playerbot/playerbot.h:3:1: error: ‘vector’ in namespace ‘std’ does not name a type
 std::vectorstd::string split(const std::string &s, char delim);
 ^
compilation terminated due to -Wfatal-errors.
make[2]: **\* [src/plugins/CMakeFiles/plugins.dir/playerbot/RandomPlayerbotFactory.cpp.o] Error 1
make[1]: **\* [src/plugins/CMakeFiles/plugins.dir/all] Error 2
make: **\* [all] Error 2

**Comment by momokli** [comment]
I REALLY dont know what happened. I compiled from one commit earlier and it worked but there were no playerbots. So I updated the local clone of the git to the newest version and compiled. It worked. But now it says "Playerbot system is currently disabled!"
Should I open a new issue?

**Comment by Esserg** [comment]
whats rev. you compiled?

**Comment by momokli** [comment]
you mean this? https://github.com/ike3/mangosbot/commit/f9fcae489348e354a11bbc02211c60185e1d3bca

fixed it anyways: https://github.com/ike3/mangosbot/issues/40
