### ISSUE TITLE
CppUnit compile on linux

### ISSUE THREAD

**Issue by ike3** [ike3/mangosbot#5]
Compile errors on linux if TESTS=1 (CppUnit core, not tests themselves). Windows build is fine.

**Comment by shooter556** [comment]
I noticed that most errors occur "high/low captials" issues.

**Comment by krlloyd** [comment]
Can you post the compile errors?

**Comment by Esserg** [comment]
Cmake error on Debian 7
http://pastebin.com/sbfWsLby

**Comment by ghost** [comment]
Ah, yes. If your Linux cmake version is above 3.1.0, you will get cmake errors. Just as if your cmake version is below 2.8.9 (but with slightly different errors). It works on Windows, though, even up to 3.2.1 (with patched FindOpenSSL.cmake macro).

The issue in both cases is in the cmake macros.

**Comment by Esserg** [comment]
Package: cmake
Version: 2.8.12.2-0ubuntu3

When i use cmake without precompiled headers, cmake work correctly:
-DUSE_SCRIPTPCH =0 -DUSE_COREPCH =0
But in this way appear compile error.
http://pastebin.com/dphNe9en

**Comment by ghost** [comment]
Are you able to compile pure, unchanged, clean TrinityCore 3.3.5 source on Ubuntu and Debian 7?
If you can make default TrinityCore source, branch 3.3.5 work, you need to compare the cmake macros and see what is wrong with the macros in ike3's source. (BTW, the Playerbot plugin code needs a real spring cleaning, it causes 80 lines of warnings, even if it works to compile on Windows.)

Edit: compare with my PR here in the ike3 repo: https://github.com/ike3/mangosbot/pull/41 ( Update cmake/macros/FindOpenSSL.cmake )

**Comment by ghost** [comment]
😃 👍
