### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by sout12** [ike3/mangosbot#50]
I got the repack 3.3.5a Single Player Project, and i was wondering how to make the bots stay updated? Like i want to update the bots every time their is a new update for them. So like replace the files but i don't wanna mess anything up. So, how?

**Comment by ghost** [comment]
ike3 has neither got time to answer your question nor any influence on the "Single Player Project".
Ask the repack creator/publisher. You will either need to contact the repack publisher to get an update, or start compiling and maintaining a server core yourself. To be able to "update" a repack, you need to compile the source yourself to get the core files authserver + worldserver (.exe + conf), in addition to create the MySQL database from SQL source files in the original source.

For tutorial / guides on how to compile, see http://www.trinitycore.info
(https://www.trinitycore.info/display/tc/Installation+Guide)

Please close this issue when you are done reading my answer. ike3 is unlikely to comment.
