### ISSUE TITLE
Core freeze while generating bots

### ISSUE THREAD

**Issue by conan513** [ike3/mangosbot#55]
I put the characters and world DB on two seperated mysql server and the world db hangs  while I clear all bots and waiting for the server to randomize the new bots.

Maybe the AiPlayerbot.RandomBotLoginAtStartup do this, because this setting isn't working yet and I can't set it to zero or false in the source and all bots try to login same time and teleporting to a random place.

**Comment by ghost** [comment]
Maybe the random bots should have had some kind of sequenced login to avoid blocking the world from loading. Not sure how it should work, maybe there should be some kind of delayed queue system.

**Comment by conan513** [comment]
Update:
RandomBotLoginAtStartup works fine on linux so again Windows  is sux

http://i.imgur.com/bRkJ55b.png 890 bots generated under linux without any issue

**Comment by conan513** [comment]
yep it's totally working on linux 

http://i.imgur.com/rITX4uc.png 5000~ bots
http://take.ms/ynXla

https://www.youtube.com/watch?v=lxPhSn_Lkwc

**Comment by ghost** [comment]
Hmm. Maybe Windows has a weakness in CPU or process thread handling that Linux don't have, so the code would need some kind of exception or for generating bots and add a FIFO for Windows.

**Comment by conan513** [comment]
seems this issue solved
