### ISSUE TITLE
Installing issues

### ISSUE THREAD

**Issue by Kittnz** [ike3/mangosbot#6]
Hi

I'm trying to get this branch working however i'm getting tons or warnings.
I get it compiled with a few warnings, but when i run the server i'm getting a lot of database errors.

At random:
Warning: GetUInt32() on non-(medium)int field. Using type: TINY.

When rndbot init is put in console.
Warning: GetUInt64() on non-bigint field. Using type: LONG.

I'm using the normal characters and auth database from TC. Without any modifications.

Also i can add a bot with ".bot add Eolap" for example but it's just standing at a starting zone doing nothing but standing.

Some warnings in server.log:
Warning: Transaction only holds 1 query, consider removing Transaction context in code.
(getting tons of these)

Hope you can give some insight into this.

**Comment by Kittnz** [comment]
After looking around in the SQL logs and your code i saw that almost everything is uint32 and a few of them shouldn't be.

**Comment by ike3** [comment]
```
.bot add Eolap
```

I suppose this is not a random bot but a character from your account. First, invite him to the group, then go find him and command "follow". There are lot of guides on the site, e.g. http://ike3.github.io/mangosbot-docs/doc/playerbot/QuickStart.html

Also it is possible to cheat a bit and go to an innkeeper, select it and give bot the command "home". Then the inn becomes bot's home place and usual "u [Hearthstone]" command will teleport him to the inn. Warlock spells, meeting stones also can be uses as normal.

These warnings can be fixed but they don't affect the AI at all.
