### ISSUE TITLE
Compiler error on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by momokli** [ike3/mangosbot#62]
`../../plugins/libplugins.a(CustomStrategy.cpp.o): In function `ai::CustomStrategy::InitTriggers(std::list<ai::TriggerNode*, std::allocator<ai::TriggerNode*> >&)':
CustomStrategy.cpp:(.text+0xba0): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator(__gnu_cxx::__normal_iterator<char const*, std::string>, __gnu_cxx::__normal_iterator<char const*, std::string>, std::basic_regex<char, std::regex_traits<char> > const&, std::bitset<11ul>)'
CustomStrategy.cpp:(.text+0xbb9): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::regex_iterator()'
CustomStrategy.cpp:(.text+0xbce): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator!=(std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> > const&)'
CustomStrategy.cpp:(.text+0xbf7): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator*()'
CustomStrategy.cpp:(.text+0xd3e): undefined reference to `std::regex_iterator<__gnu_cxx::__normal_iterator<char const*, std::string>, char, std::regex_traits<char> >::operator++()'
collect2: error: ld returned 1 exit status
make[2]: *** [src/server/worldserver/worldserver] Error 1
make[1]: *** [src/server/worldserver/CMakeFiles/worldserver.dir/all] Error 2
make: *** [all] Error 2`

**Comment by ghost** [comment]
Any chance you could post that directly on http://paste.ubuntu.com/ and link it here? :-)
The way it looks now, it is hard to read properly to get an idea of what is going on.
That kind of output is usually more formatted on the dump screen.

**Comment by momokli** [comment]
sure =)
[Here you go.](http://paste.ubuntu.com/15008704/)

[This file has errors?](https://github.com/ike3/mangosbot/blob/trinity-wotlk-ai/src/plugins/playerbot/strategy/CustomStrategy.cpp) or is it just a linux problem?

Has the last commit been compiled successfully yet? @conan513 do you know anything about it?

Any more information needed?

**Comment by momokli** [comment]
Fixed using [this](https://github.com/LordPsyan/LordPsyanBots/issues/10#issuecomment-183906973).

**Comment by ghost** [comment]
Sorry about the delay, I have had some personal issues and other challenges to overcome.
I hope you were able to fix your issue in a fairly simple way. I was hoping to compile it in Windows,
but other things got in the way (real life and other things).

**Comment by momokli** [comment]
No problem at all! :)
