### ISSUE TITLE
Worldserver keep crashing

### ISSUE THREAD

**Issue by NerdCraft99** [ike3/mangosbot#67]
**Description**:worldserver keep's crashing

can't keep it up even for 30 sec without crashing, setting AiPlayerbot.Enabled = 0 fix the crashing. I don't have any other costum patches, just your source.

**Branch(es)**:  trinity-wotlk-ai

**TDB version**:  335.61_2016_04_11

**Operating system**:  Windows 10 PRO 64

[//]: # (This template is for problem reports, for other type of reports edit it accordingly)
[//]: # (If this is a crash report, include the crashlog with https://gist.github.com/)

[crash.log](https://github.com/ike3/mangosbot/files/299112/55b583d1726f._worldserver.exe_.5-6_1-47-35.txt)

[worldserver.log](https://github.com/ike3/mangosbot/files/299114/Server.txt)

[aiplayerbot.conf.txt](https://github.com/ike3/mangosbot/files/299116/aiplayerbot.conf.txt)

**Comment by conan513** [comment]
https://github.com/ike3/mangosbot/issues/58

**Comment by NerdCraft99** [comment]
ty mate that fixed the crashing

**Comment by tkrokli** [comment]
@NerdCraft99 : I guess you can close this issue, then? :-)
