### ISSUE TITLE
bots dont cast spells

### ISSUE THREAD

**Issue by DuB1986** [ike3/mangosbot#73]
Randombots dont cast spells, buffs, do just melee
Branch: trinity-wotlk-ai

no merging, no custom mods, just used ike's repo
clone it, cmaked it and compiled
got a few warnings while compile but no errors, everything else works fine
win 10 64 bit
mysql 5.6
cmake 3.3.2
boost 1.61
virtual studio 2015 64bit

**Comment by DuB1986** [comment]
compiled playerbot trinity core, without any mods,got a few warnings, but was suscessful, everthings fine, bots just dont cast spells on their own. win 10
visual studio 15 64bit 
cmake 3.3.2

boost 1.61

**Comment by worm0508** [comment]
You must extract enUS DBC
Mangosbot doesn‘t support other languages

**Comment by DuB1986** [comment]
that fixed it, thank you very much, took me 2 days of my life, you saved me from wasting more! +rep
