### ISSUE TITLE
[TC] Warlock pet is not attacking

### ISSUE THREAD

**Issue by ike3** [ike3/mangosbot#8]
Seems works fine in R2 but something is missing in TC branch

**Comment by dmanbob** [comment]
thanks for looking into so many things I confirmed this bug too :)

**Comment by conan513** [comment]
first time when a warlock summon a pet, the pet state set to passive
maybe the warlock bots pet state is passive too

(in R2 it is set to defensive by default or I remember wrong)

**Comment by ike3** [comment]
Seems it was fixed in TC itself as on the latest version warlock imp do attack the target. But it does not cast firebolt for some reason. There is a code which sets all spells to auto-cast for both hunter and warlock pet. Hunter pet is ok but warlock is not.
